-- AUTOGENERATED
---@diagnostic disable: undefined-field, inject-field
local me=...
local hlp=LibStub('AceAddon-3.0'):GetAddon(me)
function hlp:loadHelp()
self:HF_Title([[Quick Item Level Display]],[[RELNOTES]])
self:HF_Paragraph('Description')
self:Wiki([[
=ItemLevelDisplay adds a tiny layer on each item slot with the following information:=

 * ItemLevel
 * Socket Status
 * Enchant Status


==ItemLevelDisplay manages==
* Paperdoll
* Inspect Frame
* Transmogrifier
* Bags and Bank (if your bag addon is unsupported, please let me know it)

Bags management is implemented via separated addon!! (ILD-<bagmanager name>)


==Bag manager list:==
* ILD-Blizzard: Blizzard (with bank)
* ILD-Arkinventory: ArkInventory (with bank)
* ILD-Baggins: Baggins (with bank)
* ILD-Baudbag: Baud Bag (with bank)
]])
self:HF_Paragraph('Release Notes')
self:RelNotes(2,15,0,[[
Fix: work in progress
]])
self:RelNotes(2,14,3,[[
Feature: Removed old stubs
]])
self:RelNotes(2,14,2,[[
Toc: 11.0.7
Feature: Version 2.14.2
]])
self:RelNotes(2,14,0,[[
Fix: Removed baggins and BaudBag
Fix: removed no longer usefull Ild-Arkinventory
Fix: No Longer use LibItemUpgradeInfo
]])
self:RelNotes(2,9,1,[[
Toc: Version 11.0.2
Fix: Relnotes Error
]])
self:RelNotes(2,8,1,[[
Toc: Version 10.2.7
Feature: Removed Bagnon support, use Bagnon ItemLevel
Feature: Removed Combuctor support, use Bagnon ItemLevel
Feature: Removed LiteBag support, use LiteBag Item Level
Feature: Removed Onebag3 support
]])
self:RelNotes(2,7,2,[[
Fix: Removed chat spam
Fix: Removed getItemlink error
]])
self:RelNotes(2,7,0,[[
Toc: Version 10.2.5
]])
self:RelNotes(2,2,3,[[
Fix: Repackaged to pull the right MSADropdown version
]])
self:RelNotes(2,2,2,[[
Fix: LiteBag works again
]])
self:RelNotes(2,2,1,[[
Fix: Enables baudbag
]])
self:RelNotes(2,2,0,[[
Toc: 9.0.1
]])
self:RelNotes(2,1,6,[[
Fix: Bagnon related error thanks to Fauxfox
]])
self:RelNotes(2,1,5,[[
Toc: 8.3.0
]])
self:RelNotes(2,1,4,[[
Toc: 8.2.0
]])
self:RelNotes(2,1,2,[[
Fix: Works again with Bagnon
]])
self:RelNotes(2,1,1,[[
Fix: Should again show missing enchants
]])
self:RelNotes(2,0,18,[[
Fix: Small fixes to ArkInventory and Combuctor
]])
self:RelNotes(2,0,14,[[
Fix: Some localizations (non latin ones) were broken
]])
self:RelNotes(2,0,12,[[
Fix: Correct itemlevel for artifacts hopefully shown in inspect window, too
]])
self:RelNotes(2,0,10,[[
Fix: Bag shadow was not remembered
Fix: Upgraded Item level library
]])
self:RelNotes(2,0,9,[[
Fix: Crash on logout
]])
self:RelNotes(2,0,6,[[
Fix: ItemLevel in Blizzard bags is now back
]])
self:RelNotes(2,0,4,[[
Toc: 7.1.0 compatible
]])
self:RelNotes(2,0,3,[[
Fix: ItemLevelDisplay\ItemLevelDisplay-2.0.2.lua
]])
self:RelNotes(2,0,2,[[
Feature: font type and font size are now totally customizable
Feature: itemlevel display in bags can be disabled under a customizable itemlevel
Fix: Socket status is back
Fix: Arkinventory was always showing itemelevel regardless enabled itemclasses
]])
self:RelNotes(2,0,1,[[
Feature: you can choose for which items' classes show the itemlevel
Feature: item scanning is now much faster for all addons
Fix: added switch to completely disable itemlevel in bags
]])
self:RelNotes(2,0,0,[[
Feature: Added Inspect Frame
Feature: Blizzard bags support
Feature: Arkinventory bags support
Fix: Removed useless total gem count
]])
self:RelNotes(1,7,1,[[
Fix: Message
]])
self:RelNotes(1,7,0,[[
Feature: Heirloom current level is now displayed
]])
self:RelNotes(1,6,2,[[
Fixed: An error occurs when login
]])
self:RelNotes(1,6,1,[[
Feature: You can disable itemlevel for shirt and tabard
Feature: Dropped buckle reference
Fixed: Error "Message
]])
self:RelNotes(1,6,0,[[
Feature: No longer shows old enchant requiremente for item 600+
]])
self:RelNotes(1,5,5,[[
Fixed: Removes debug spam from chat
Update: Will remove old enchant/buckles info in 1.6.0
]])
self:RelNotes(1,5,4,[[
Fixed: Error when opening equipmentset flyout with nore than one equipment set
]])
self:RelNotes(1,5,3,[[
Fixed: Opening a flyout in trasmogrification panel, when no flyout was ever open in the standard paperdoll raised
]])
self:RelNotes(1,5,2,[[
Fixed: In some cases, opening the flyout caused error spamming (signaled by Phosphoros)
]])
self:RelNotes(1,5,1,[[
Fixed: No longer gives error when opening tabard or shirt flyout.
]])
self:RelNotes(1,5,0,[[
Feature: Equipment in flyout equipment manager buttons are now taken in consideration and ilevel added to them.
]])
self:RelNotes(1,4,5,[[
Fixed: now accounts for bonus level due to difficulty in raid dropped items. With this release upgrade for Wod should be now complete
]])
self:RelNotes(1,4,4,[[
Fixed: when you install ItemLevelDisplay for tha absolute first time, it raises an error if you choose "Common profile for all characters" at the one time profile type request.
]])
self:RelNotes(1,4,3,[[
Fixed: For level based coloring, upgrade value was not taken in account.
Feature: Thanks to Mergele for sending the fix
]])
self:RelNotes(1,4,2,[[
Fixed: Upgraded items are back!!
]])
self:RelNotes(1,4,1,[[
Upgrade: libItemUpgradeInfo upgraded to 1.0.7
]])
self:RelNotes(1,3,2,[[
Feature: Configuration can now be global.(i.e. all characters share the same settings)
Fixed: Best green and best red were swapped
]])
self:RelNotes(1,3,1,[[
Feature: Refined configuration panel
Feature: Added enchantable rings for enchanter
Fixed: gem mini panel is now always updated
]])
self:RelNotes(1,3,0,[[
Feature: Refactored appearance with now 4 color schemes
* Quality: based on item quality from poor to Heirloom
* Plain: no color at all
* Level green: based on relative level (green are best)
* Level red: based on relative level (red are best)
Feature: Thanks to KVLtv for donating the code
]])
self:RelNotes(1,2,7,[[
Upgrade: Accounts for 5.4.8 item upgrades
]])
self:RelNotes(1,2,6,[[
Upgrade: Accounts for 5.4 item upgrades
]])
self:RelNotes(1,2,4,[[
Feature: More localization
]])
self:RelNotes(1,1,2,[[
Upgrade: Accounts for 5.3 item upgrades
]])
self:RelNotes(1,1,0,[[
Upgrade: Accounts for 5.1 item upgrades
Feature: Level text can now be moved via /ild gui
]])
self:RelNotes(1,0,8,[[
Fixed: Head slot is no longer enchantable
]])
self:RelNotes(1,0,5,[[
Feature: Now you can reverse color (red itemes are better)
]])
self:RelNotes(1,0,3,[[
Fixed: Removed chat spam  18 [Name of item in slot 18] item type
Feature: Config menu via blizzard menu or /ild gui
]])
self:RelNotes(1,0,2,[[
Fixed: Waist slot no longer display -1 when you have a belt buckle filled
Fixed: Now only guns/bows/crossbows should check for enchants
]])
self:RelNotes(1,0,1,[[
Fixed: Waist slot was ignored
]])
self:RelNotes(1,0,0,[[
Feature: Initial release
]])
self:RelNotes(0,14,1,[[
]])
end
